- name: Add grafana key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add repository for grafana
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present 

- name: Install grafana
  ansible.builtin.apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Start grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes