- name: Create /tmp/node_exporter
  ansible.builtin.file:
    path: /tmp/node_exporter
    state: directory
    mode: 0755

- name: Download node_exporter tar file
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter
    remote_src: yes

- name: Find node_exporter file name
  ansible.builtin.find:
    use_regex: yes
    paths: /tmp/node_exporter
    patterns: "node_exporter*"
    file_type: directory
  register: node_exporter_file
  

- name: Copy node_exporter binary to /usr/local/bin
  ansible.builtin.copy:
    src: "{{node_exporter_file.files[0].path +'/node_exporter'}}"
    dest: /usr/local/bin/node_exporter
    mode: 0755
    remote_src: yes

- name: Copy node_exporter systemd unit file to /etc/systemd/system
  ansible.builtin.copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter service
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: yes