---

- hosts: linux
  become: yes
  
  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install package need for jenkins
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: ['openjdk-11-jdk']

    - name: Add jenkins key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

        
        

    - name: Add jenkins repository
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/

    - name: Install jenkins
      ansible.builtin.apt:
        name: jenkins
        state: latest
        update_cache: yes
        