---

- hosts: all
  become: yes
  vars:
    install_package: "no"
    install_golang: "no"
    install_docker: "no"
    install_ansible: "no"

  tasks:

  - name: Install package 
    import_tasks: start_package.yml
    when: install_package == "yes"
  
  - name: Install golang
    import_tasks: golang.yml
    when: install_golang == "yes"

  - name: Install docker 
    import_tasks: docker.yml
    when: install_docker == "yes"

  - name: Install ansible
    import_tasks: ansible.yml
    when: install_ansible == "yes"