--- 

- hosts: all
  become: yes

  tasks:

  - name: Add apt key from a url
    ansible.builtin.apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present

  - name: Add apt repository
    ansible.builtin.apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present

  - name: Install helm
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop: ["apt-transport-https","helm"]